######################################################################
# Automatically generated by qmake (3.1) Thu Jan 12 20:12:40 2023
######################################################################

TEMPLATE = app
TARGET = qml_test
INCLUDEPATH += . src/

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

QT += widgets quick network core

#CONFIG += DEBUG
CONFIG+=qml_debug

QMAKE_CXXFLAGS+= -g

LIBS +=  -L"/usr/lib/" -lwiringPi

# Input
HEADERS += src/gpios.h \
           src/irc.h  \
           src/secret.h \ 
           modules/ADC/adcController.h \
            modules/UART/uartController.h \
            modules/UART/receiverThread.h \

SOURCES +=  main.cpp \
            src/gpios.cpp \
            src/irc.cpp   \
            modules/ADC/adcController.cpp \
            modules/UART/uartController.cpp \
            modules/UART/receiverThread.cpp \

